input {
  tcp {
    port => 5000
    codec => json_lines {
      ecs_compatibility => disabled
      decode_size_limit_bytes => 16777216
    }
  }
}

filter {
  if ![ecs][version] {
    drop {}
  }
}

output {
  elasticsearch {
    hosts => ["http://elasticsearch:9200"]
    index => "local-spring-logs-%{+YYYY.MM.dd}"
  }
}
