info:
  name: decrypt
  type: http
  seq: 8

http:
  method: POST
  url: http://localhost:8071/decrypt
  headers:
    - name: Content-Type
      value: text/plain
    - name: User-Agent
      value: insomnia/10.1.1
  body:
    type: text
    data: 43e81a570e0e9ae4af2e2c15e562c8d5c6a1366f78fca8559d5c9cbef5dd4a7e
  auth: inherit

settings:
  encodeUrl: true
  timeout: 0
  followRedirects: false
  maxRedirects: 5

docs: |
  Imported from HAR file 'Insomnia_2025-09-28.har'
  Created by Insomnia REST Client insomnia.desktop.app:v11.6.1

  Infos about the HAR entry:

  ## Timings

  Send HTTP request: 0 ms
  Wait HTTP response: 3.3 ms
  Receive HTTP response: 0 ms

  ## Response

  ### Headers

  ```
  HTTP/1.1 200 
  Content-Type: text/plain;charset=UTF-8
  Content-Length: 8
  Date: Tue, 19 Nov 2024 22:50:28 GMT
  ```

  ### Body

  postgres
