info:
  name: Organization > dev
  type: http
  seq: 1

http:
  method: GET
  url: http://localhost:8071/organization-service/dev
  headers:
    - name: User-Agent
      value: insomnia/10.1.1
  body:
    type: text
    data: ""
  auth: inherit

settings:
  encodeUrl: true
  timeout: 0
  followRedirects: false
  maxRedirects: 5

docs: |
  Imported from HAR file 'Insomnia_2025-09-28.har'
  Created by Insomnia REST Client insomnia.desktop.app:v11.6.1

  Infos about the HAR entry:

  ## Timings

  Send HTTP request: 0 ms
  Wait HTTP response: 0 ms
  Receive HTTP response: 0 ms

  ## Response

  ### Headers

  ```
  HTTP/1.1 0 
  ```
