name: deployment

services:
  organization_db:
    image: postgres:18-alpine
    ports:
      - "15432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_DB=ostock_dev
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ./compose/organization/:/docker-entrypoint-initdb.d/
    networks:
      - organization
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 15s
      timeout: 5s
      retries: 10
  licensing_db:
    image: postgres:18-alpine
    ports:
      - "25432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_DB=ostock_dev
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ./compose/licensing/:/docker-entrypoint-initdb.d/
    networks:
      - licensing
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 15s
      timeout: 5s
      retries: 10
  config-service:
    image: ostock/config-server:1.0.0-SNAPSHOT
    ports:
      - "8071:8071"
    networks:
      - config
    environment:
      THC_PATH: /actuator/health
      THC_PORT: "8071"
    healthcheck:
      test: [ "CMD", "/workspace/health-check" ]
      interval: 5s
      timeout: 5s
      retries: 12
  eurekaserver:
    image: ostock/eureka-server:0.0.1-SNAPSHOT
    ports:
      - "8070:8070"
    depends_on:
      config-service:
        condition: service_healthy
    networks:
      - config
      - eureka
    environment:
      spring.profiles.active: "docker"
  organization-service:
    image: ostock/organization-service:0.0.1-SNAPSHOT
    depends_on:
      config-service:
        condition: service_healthy
      organization_db:
        condition: service_healthy
    ports:
      - "8081:8081"
    networks:
      - organization
      - config
      - eureka
    environment:
      spring.profiles.active: "docker"
  licensing-service:
    image: ostock/licensing-service:0.0.1-SNAPSHOT
    depends_on:
      config-service:
        condition: service_healthy
      licensing_db:
        condition: service_healthy
    ports:
      - "8080:8080"
    networks:
      - config
      - eureka
      - licensing
      - organization
    environment:
      spring.profiles.active: "docker"

networks:
  config:
  eureka:
  organization:
  licensing:
