CREATE TABLE IF NOT EXISTS public.organization
(
    organization_id bigint GENERATED BY DEFAULT AS IDENTITY,
    name            text,
    contact_name    text,
    contact_email   text,
    contact_phone   text,
    CONSTRAINT organizations_pkey PRIMARY KEY (organization_id)
);

ALTER TABLE public.organization
    OWNER TO postgres;
